#!/usr/bin/env python3
"""Embed the committed eval snapshot into the dashboard as a JS module.

The dashboard is a zero-build static page; it reads ``window.RELAY_REPORT`` from
this generated file so it works from any static host and from ``file://`` with no
fetch/CORS step. Regenerate after `relay eval`:

    python scripts/build_dashboard_data.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "results" / "demo" / "eval-report.json"
OUT = ROOT / "dashboard" / "report-data.js"


def main() -> int:
    report = SNAPSHOT.read_text(encoding="utf-8").rstrip("\n")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_dashboard_data.py — do not edit by hand.\n"
        f"window.RELAY_REPORT = {report};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
